osuosl/climesync

- climesync.py
Fixes issue #9 and the "cp" command
> Fixed bug preventing new project creation

- README.md
- climesync.py
@matthewrsj @Kennric Could you please test this fix?
> Fixed issue #1

- README.md
- climesync.py
@matthewrsj @Kennric Could you review this?
Fixes issues #5 #6 #7 #8
> Added commands to delete times, users, activities, and projects

- README.md
- climesync.py
Now climesync has been reorganized and refactored in a way that should make it easier to work on in the future. Aside from separating menu options into different functions, notable changes include:
print_json(): A new function to print pymesync responses. PrettyPrinter didn't print things in a very human-readable format
get_field() and get_fields(): A new set of functions to handle getting user input of different types and collecting those responses into a dictionary to send to pymesync.
A disconnect option for completeness' sake
This PR closes #3 and #4
> Refactored everything

- climesync.py
Format strings using the old binary % operator were updated to use the newer str.format() method
Closes #18
> Updated old format strings to str.format()

- README.md
- climesync.py
By using the new "st" menu option, users can now view the total amount of time worked on a project and view the time worked between optional start and end dates.
Closes #13
> Added option to sum total time worked on a project

- climesync.py
Users and user permissions can now be added when creating projects or updating them.
Closes #12
> Added ability to add users to new projects and update projects with users

- climesync.py
- requirements.txt
Fixed issues with PEP8 compliance
Closes #22
> Made Climesync PEP8-compliant

- .travis.yml
- climesync.py
- requirements.txt
- testing/climesync_test.py
More unit tests should be added in the future, but by merging this into master now it will at least take care of code linting and basic Travis integration
> Merge cohenaa/write-unit-tests into master

- climesync.py
Changed the menu behavior to not appear after every call and fixed some spacing issues in print_json().
Fixes #21
> Improved the user interface

- LICENSE
> Added Apache v2 License

- climesync.py
- testing/time_format_test.py
Fixes issue #32 
1. Run `nosetests` in the root of the project directory
2. Run the program and authenticate with TimeSync
3. Submit and update times using the new time format
4. Input the `gt` option and see that times are displayed in the new time format
@osuosl/devs
> Human readable time input/output

- README.md
- docs/source/dev.rst
- docs/source/usage.rst
- requirements.txt
- setup.py
fixes issue #49 
1. Create a fresh virtualenv (i.e. `mkvirtualenv testenv`)
2. Run `python setup.py install`
3. Run `climesync` and see that the program runs
@osuosl/devs
> Added setup.py

- climesync.py
Fixes #45 
1. Run climesync.py and authenticate with TimeSync
2. Enter `gp`.
3. When the prompt asks for a slug, enter one.
4. Notice that the returned projects are projects that have the given slug.
@osuosl/devs
> Fix slug field

- climesync.py
fixes issue #51 
1. run `nosetests`
@osuosl/devs
> Fixed error detection code for get_times

- testing/test_data.py
1. Run `nosetests`
@osuosl/devs
> Fixed tests that were broken by most recent merge

- climesync/util.py
Git merged some things weird and now the sign-in command doesn't work
1. Run `nosetests`
2. Run climesync and use `s` to sign in as `test` with the password `test`
@osuosl/devs
> Fixed bug preventing sign-in

- testing/test_data.py
fixes issue #99 
1. Run nosetests
3. See tests pass.
@osuosl/devs
> added new summary feilds to test data

- climesync/climesync.py
- climesync/commands.py
fixes issue #89 
Blocked until LDAP support is turned on for the backend
N/A (not supported on the backend yet)
@osuosl/devs
> Added support for LDAP authentication

- climesync/util.py
Fixes #102
1. Run climesync
2. Enter `gp`
3. See the list of projects
@osuosl/devs
> Fix "get projects"
